import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const cloudSidebar: SidebarsConfig = {
  sidebar: [
    {
      type: "doc",
      id: "index",
    },
    {
      type: "category",
      label: "Secrets",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "secrets",
        },
      ],
    },
    {
      type: "category",
      label: "Package Cache",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "cache",
        },
      ],
    },
    {
      type: "category",
      label: "Deploying your Project with Jetify Deployments",
      items: [
        {
          type: "autogenerated",
          dirName: "deploys",
        },
      ],
    },
    {
      type: "category",
      label: "Teams and Projects",
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "dashboard",
        },
      ],
    },
    {
      type: "doc",
      id: "faq",
    },
  ],
};

export default cloudSidebar.sidebar;
