# syntax=docker/dockerfile:1

FROM nixos/nix:2.10.3 as base

FROM base as builder

# 1. SETUP STAGE
#    Setup the container, and install nix packages.
# -------------------------------------------------

# Setup shell so that we catch any errors early
SHELL [ "/bin/sh", "-eux", "-o", "pipefail", "-c"]
WORKDIR /scratch

# Setup nix in its own layer so it can be cached.
COPY --link ./.devbox/gen/default.nix ./.devbox/gen/
# Setup /nix/store as a cache directory.
# Declaring it as a cache directory makes it empty directory, so we need to
# specify, using from= and source=, that we want to re-copy the contents of
# the directory from nixos/nix.
RUN --mount=type=cache,target=/nix/store,from=base,source=/nix/store \
  nix-env -if ./.devbox/gen/default.nix

# 2. INSTALL STAGE
#    Install libraries needed by the source code.
# -----------------------------------------------

COPY --link . ./
RUN --mount=type=cache,target=/nix/store,from=base,source=/nix/store {{.InstallStage.Command}}

# 3. BUILD STAGE
#    Compile the source code into an executable.
# ----------------------------------------------
RUN --mount=type=cache,target=/nix/store,from=base,source=/nix/store {{.BuildStage.Command}}

# 4. PACKAGING STAGE
#    Create a minimal image that contains the executable.
# -------------------------------------------------------

# Default to :debug so we have a shell.
FROM gcr.io/distroless/base:debug
# Setup shell so that we catch any errors early
SHELL [ "/busybox/sh", "-eu", "-o", "pipefail", "-c"]

# TODO: Improve to only copy needed files and not the entire src directory.
COPY --link --from=builder /scratch/. /app/
WORKDIR /app

# 4. START STAGE
#    Execute the application inside the final container.
# ------------------------------------------------------

# We default to ENTRYPOINT instead of CMD as we consider it best practice
# when the container is wrapping an application or service.
ENTRYPOINT {{.StartStage.Command}}
