// Copyright 2023 Jetpack Technologies Inc and contributors. All rights reserved.
// Use of this source code is governed by the license in the LICENSE file.

package templates

var templates = map[string]string{
	"argo":            "examples/cloud_development/argo-workflows/",
	"maelstrom":       "examples/cloud_development/maelstrom/",
	"minikube":        "examples/cloud_development/minikube/",
	"temporal":        "examples/cloud_development/temporal/",
	"jupyter":         "examples/data_science/jupyter/",
	"llama":           "examples/data_science/llama/",
	"pytorch":         "examples/data_science/pytorch/basic-example/",
	"gradio":          "examples/data_science/pytorch/gradio/",
	"tensorflow":      "examples/data_science/tensorflow/",
	"mariadb":         "examples/databases/mariadb/",
	"postgres":        "examples/databases/postgres/",
	"redis":           "examples/databases/redis/",
	"csharp":          "examples/development/csharp/hello-world/",
	"elixir":          "examples/development/elixir/elixir_hello/",
	"fsharp":          "examples/development/fsharp/hello-world/",
	"go":              "examples/development/go/hello-world/",
	"haskell":         "examples/development/haskell/",
	"java-gradle":     "examples/development/java/gradle/hello-world/",
	"java-maven":      "examples/development/java/maven/hello-world/",
	"nim":             "examples/development/nim/spinnytest/",
	"node-npm":        "examples/development/nodejs/nodejs-npm/",
	"node-typescript": "examples/development/nodejs/nodejs-typescript/",
	"node-yarn":       "examples/development/nodejs/nodejs-yarn/",
	"php":             "examples/development/php/php8.1/",
	"python-pip":      "examples/development/python/pip/",
	"python-pipenv":   "examples/development/python/pipenv/",
	"python-poetry":   "examples/development/python/poetry/poetry-demo/",
	"ruby":            "examples/development/ruby/",
	"rust":            "examples/development/rust/rust-stable-hello-world/",
	"zig":             "examples/development/zig/zig-hello-world/",
	// "mod": "examples/flakes/go-mod/",
	// "overlay": "examples/flakes/overlay/",
	// "extension": "examples/flakes/php-extension/",
	// "php": "examples/flakes/php/",
	// "remote": "examples/flakes/remote/",
	"apache":     "examples/servers/apache/",
	"caddy":      "examples/servers/caddy/",
	"nginx":      "examples/servers/nginx/",
	"django":     "examples/stacks/django/",
	"drupal":     "examples/stacks/drupal/",
	"jekyll":     "examples/stacks/jekyll/",
	"lapp-stack": "examples/stacks/lapp-stack/",
	"lepp-stack": "examples/stacks/lepp-stack/",
	"rails":      "examples/stacks/rails/",
	"tutorial":   "examples/tutorial/",
}
