name: cli-post-release
# Finalize and announce the release once its been published on Github.

on:
  release:
    types: [released]

permissions:
  contents: write
  pull-requests: read
  id-token: write # Needed for aws-actions/configure-aws-credentials@v1

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-west-2
      - name: Update latest version in s3
        run: |
          tmp_file=$(mktemp)
          echo "${{ github.ref_name }}" > $tmp_file
          aws s3 cp $tmp_file s3://releases.jetpack.io/devbox/stable/version
