name: debug

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner type to debug on"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          - macos-12
          - ubuntu-latest

permissions:
  contents: read

env:
  HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_EMOJI: 1
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  debug:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    steps:
      - name: Get rate limits
        run: |
          curl https://api.github.com/rate_limit \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              --show-error \
              --silent \
            | jq .
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: |
          echo "Starting a tmate session for 10 minutes."
          echo
          echo "You can connect using the SSH command printed below to get an interactive shell"
          echo "on this GitHub Actions runner. Access is limited to the public SSH keys"
          echo "associated with your GitHub account."

          curl https://api.github.com/users/${{ github.actor }}/keys \
              -H "Accept: application/vnd.github+json" \
              --show-error \
              --silent \
            | jq .
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
