name: mike-test

on:
  pull_request:

permissions:
  contents: write
  pull-requests: read

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tests
        uses: ./.github/workflows/cli-tests.yaml
      - name: Notify jetpack.io slack of release status
        id: slack
        if: always()
        run: echo job is ${{ job.status }}
