name: mike-test

on:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: cause a failure
        run: exit 1
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: do something
        if: always()
        run: "echo job status: ${{ job.status }}"
