name: mike-test

on:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: tests
        uses: ./.github/workflows/cli-tests.yaml
      - name: Notify jetpack.io slack of release status
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CLI_RELEASE_WEBHOOK_URL }}
