name: Random Reviewer Assignment
on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_PR_ASSIGNMENT }}

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Randomly assign reviewer from team
        uses: actions/github-script@v6
        with:
          script: |
            const TRIAGE_USERNAME = 'Lagoja';
            
            try {
              const teamMembers = await github.rest.teams.listMembersInOrg({
                org: 'jetify-com',
                team_slug: 'eng'
              });
              
              const prAuthor = context.payload.pull_request.user.login.toLowerCase();
              console.log(`PR Author: ${prAuthor}`);
              
              // Get eligible reviewers (excluding PR author and lagoja)

              const eligibleReviewers = teamMembers.data
                .map(member => member.login)
                .filter(login => {
                  const loginLower = login.toLowerCase();
                  return loginLower !== prAuthor && loginLower !== TRIAGE_USERNAME;
                });
              
              if (eligibleReviewers.length === 0) {
                console.log('No eligible reviewers found');
                return;
              }
              
              // Build reviewers list: random reviewer + lagoja (if not PR author)
              const randomReviewer = eligibleReviewers[Math.floor(Math.random() * eligibleReviewers.length)];
              const reviewers = [randomReviewer];
              
              if (prAuthor !== TRIAGE_USERNAME) {
                reviewers.push(TRIAGE_USERNAME);
              }
              
              console.log(`Assigning reviewers: ${reviewers.join(', ')}`);
              
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers
              });
              
            } catch (error) {
              console.error('Error assigning reviewer:', error);
            }
